set -g fish_color_normal F2E6C2
set -g fish_color_command F24535
set -g fish_color_param 8EC9C9
set -g fish_color_error FF6A5A
set -g fish_color_quote E6B85C
set -g fish_color_redirection 498C8C
set -g fish_color_end A65D85
set -g fish_color_autosuggestion 3A3533
set -g fish_color_selection --background=CAC2A4
set -g fish_color_search_match --background=CAC2A4
set -g fish_color_cwd 6AAB9C
set -g fish_color_cwd_root F24535
set -g fish_color_user 6AAB9C
set -g fish_color_host 8EC9C9
set -g fish_color_operator 498C8C
set -g fish_color_escape 8EC9C9
set -g fish_color_comment CAC2A4
