# Colors (Noctalia)

[colors.bright]
black = '#463b38'
blue = '#c86d45'
cyan = '#c4856a'
green = '#8b9a5a'
magenta = '#cc8977'
red = '#d47761'
white = '#e6dbd3'
yellow = '#dbb98f'

[colors.cursor]
cursor = '#b85a30'
text = '#1d1816'

[colors.normal]
black = '#1d1816'
blue = '#b85a30'
cyan = '#c4856a'
green = '#8b9a5a'
magenta = '#cc8977'
red = '#c25d4e'
white = '#b8aca2'
yellow = '#d8a657'

[colors.primary]
background = '#231d1b'
foreground = '#e6dbd3'

[colors.selection]
background = '#b8aca2'
text = '#1d1816'
